version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:8.3.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # networks:
    #   - elk
  
  kibana:
    image: kibana:8.3.2
    container_name: kibana
    ports:
      - 5601:5601
    # networks:
    #   - elk
  
  logstash:
    image: logstash:8.3.2
    container_name: logstash
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
    # networks:
    #   - elk

# networks:
#   elk:
#     driver: bridge
